//Cities Actions
export const FETCH_CITIES = 'FETCH_CITIES'
export const NEW_CITY = 'NEW_CITY'
export const REMOVE_CITY = 'REMOVE_CITY'
export const EDIT_CITY = 'EDIT_CITY'
//Norris Actions
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CHUCKJOKE = 'FETCH_CHUCKJOKE'
export const FETCH_SOMEONEELSEJOKE = 'FETCH_SOMEONEELSEJOKE'
export const FETCH_CHUCKJOKEWITHCATEGORY = 'FETCH_CHUCKJOKEWITHCATEGORY'
//Joke actions
export const FETCH_JOKE = 'FETCH_JOKE'
export const FETCH_TENJOKES = 'FETCH_TENJOKES'

//Dog actions
export const FETCH_DOG = 'FETCH_DOG'
export const DOWNLOAD_DOG = 'DOWNLOAD_DOG'
export const DOG_CLICK_THUMBNAIL = 'DOG_CLICK_THUMBNAIL'
